name: kzSpells
version: '${version}'
main: com.cludivers.kz2wdprison.Kz2wdPrison
api-version: 1.19
commands:
  xp:
    description: xp utility
  mine:
    description: mine utility
  nation:
    description: nation utility
  artifact:
    description: artifact utility
  intrinsic:
    description: intrinsic utility
  shardland:
    description: shardland utility