package com.cludivers.kz2wdprison.gameplay.artifact.effects

import org.bukkit.Material

object MaterialCosts {

    fun getMaterialCost(material: Material): Int {
        return when(material){
            Material.AIR -> 0
            Material.STONE -> 10
            Material.GRANITE -> 10
            Material.POLISHED_GRANITE -> 10
            Material.DIORITE -> 10
            Material.POLISHED_DIORITE -> 10
            Material.ANDESITE -> 10
            Material.POLISHED_ANDESITE -> 10
            Material.DEEPSLATE -> 10
            Material.COBBLED_DEEPSLATE -> 10
            Material.POLISHED_DEEPSLATE -> 10
            Material.CALCITE -> 10
            Material.TUFF -> 10
            Material.DRIPSTONE_BLOCK -> 10
            Material.GRASS_BLOCK -> 10
            Material.DIRT -> 10
            Material.COARSE_DIRT -> 10
            Material.PODZOL -> 10
            Material.ROOTED_DIRT -> 10
            Material.MUD -> 10
            Material.CRIMSON_NYLIUM -> 10
            Material.WARPED_NYLIUM -> 10
            Material.COBBLESTONE -> 10
            Material.OAK_PLANKS -> 10
            Material.SPRUCE_PLANKS -> 10
            Material.BIRCH_PLANKS -> 10
            Material.JUNGLE_PLANKS -> 10
            Material.ACACIA_PLANKS -> 10
            Material.DARK_OAK_PLANKS -> 10
            Material.MANGROVE_PLANKS -> 10
            Material.BAMBOO_PLANKS -> 10
            Material.CRIMSON_PLANKS -> 10
            Material.WARPED_PLANKS -> 10
            Material.BAMBOO_MOSAIC -> 10
            Material.OAK_SAPLING -> 10
            Material.SPRUCE_SAPLING -> 10
            Material.BIRCH_SAPLING -> 10
            Material.JUNGLE_SAPLING -> 10
            Material.ACACIA_SAPLING -> 10
            Material.DARK_OAK_SAPLING -> 10
            Material.MANGROVE_PROPAGULE -> 10
            Material.BEDROCK -> 10
            Material.SAND -> 10
            Material.RED_SAND -> 10
            Material.GRAVEL -> 10
            Material.COAL_ORE -> 10
            Material.DEEPSLATE_COAL_ORE -> 10
            Material.IRON_ORE -> 10
            Material.DEEPSLATE_IRON_ORE -> 10
            Material.COPPER_ORE -> 10
            Material.DEEPSLATE_COPPER_ORE -> 10
            Material.GOLD_ORE -> 10
            Material.DEEPSLATE_GOLD_ORE -> 10
            Material.REDSTONE_ORE -> 10
            Material.DEEPSLATE_REDSTONE_ORE -> 10
            Material.EMERALD_ORE -> 10
            Material.DEEPSLATE_EMERALD_ORE -> 10
            Material.LAPIS_ORE -> 10
            Material.DEEPSLATE_LAPIS_ORE -> 10
            Material.DIAMOND_ORE -> 10
            Material.DEEPSLATE_DIAMOND_ORE -> 10
            Material.NETHER_GOLD_ORE -> 10
            Material.NETHER_QUARTZ_ORE -> 10
            Material.ANCIENT_DEBRIS -> 10
            Material.COAL_BLOCK -> 10
            Material.RAW_IRON_BLOCK -> 10
            Material.RAW_COPPER_BLOCK -> 10
            Material.RAW_GOLD_BLOCK -> 10
            Material.AMETHYST_BLOCK -> 10
            Material.BUDDING_AMETHYST -> 10
            Material.IRON_BLOCK -> 10
            Material.COPPER_BLOCK -> 10
            Material.GOLD_BLOCK -> 10
            Material.DIAMOND_BLOCK -> 10
            Material.NETHERITE_BLOCK -> 10
            Material.EXPOSED_COPPER -> 10
            Material.WEATHERED_COPPER -> 10
            Material.OXIDIZED_COPPER -> 10
            Material.CUT_COPPER -> 10
            Material.EXPOSED_CUT_COPPER -> 10
            Material.WEATHERED_CUT_COPPER -> 10
            Material.OXIDIZED_CUT_COPPER -> 10
            Material.CUT_COPPER_STAIRS -> 10
            Material.EXPOSED_CUT_COPPER_STAIRS -> 10
            Material.WEATHERED_CUT_COPPER_STAIRS -> 10
            Material.OXIDIZED_CUT_COPPER_STAIRS -> 10
            Material.CUT_COPPER_SLAB -> 10
            Material.EXPOSED_CUT_COPPER_SLAB -> 10
            Material.WEATHERED_CUT_COPPER_SLAB -> 10
            Material.OXIDIZED_CUT_COPPER_SLAB -> 10
            Material.WAXED_COPPER_BLOCK -> 10
            Material.WAXED_EXPOSED_COPPER -> 10
            Material.WAXED_WEATHERED_COPPER -> 10
            Material.WAXED_OXIDIZED_COPPER -> 10
            Material.WAXED_CUT_COPPER -> 10
            Material.WAXED_EXPOSED_CUT_COPPER -> 10
            Material.WAXED_WEATHERED_CUT_COPPER -> 10
            Material.WAXED_OXIDIZED_CUT_COPPER -> 10
            Material.WAXED_CUT_COPPER_STAIRS -> 10
            Material.WAXED_EXPOSED_CUT_COPPER_STAIRS -> 10
            Material.WAXED_WEATHERED_CUT_COPPER_STAIRS -> 10
            Material.WAXED_OXIDIZED_CUT_COPPER_STAIRS -> 10
            Material.WAXED_CUT_COPPER_SLAB -> 10
            Material.WAXED_EXPOSED_CUT_COPPER_SLAB -> 10
            Material.WAXED_WEATHERED_CUT_COPPER_SLAB -> 10
            Material.WAXED_OXIDIZED_CUT_COPPER_SLAB -> 10
            Material.OAK_LOG -> 10
            Material.SPRUCE_LOG -> 10
            Material.BIRCH_LOG -> 10
            Material.JUNGLE_LOG -> 10
            Material.ACACIA_LOG -> 10
            Material.DARK_OAK_LOG -> 10
            Material.MANGROVE_LOG -> 10
            Material.MANGROVE_ROOTS -> 10
            Material.MUDDY_MANGROVE_ROOTS -> 10
            Material.CRIMSON_STEM -> 10
            Material.WARPED_STEM -> 10
            Material.BAMBOO_BLOCK -> 10
            Material.STRIPPED_OAK_LOG -> 10
            Material.STRIPPED_SPRUCE_LOG -> 10
            Material.STRIPPED_BIRCH_LOG -> 10
            Material.STRIPPED_JUNGLE_LOG -> 10
            Material.STRIPPED_ACACIA_LOG -> 10
            Material.STRIPPED_DARK_OAK_LOG -> 10
            Material.STRIPPED_MANGROVE_LOG -> 10
            Material.STRIPPED_CRIMSON_STEM -> 10
            Material.STRIPPED_WARPED_STEM -> 10
            Material.STRIPPED_OAK_WOOD -> 10
            Material.STRIPPED_SPRUCE_WOOD -> 10
            Material.STRIPPED_BIRCH_WOOD -> 10
            Material.STRIPPED_JUNGLE_WOOD -> 10
            Material.STRIPPED_ACACIA_WOOD -> 10
            Material.STRIPPED_DARK_OAK_WOOD -> 10
            Material.STRIPPED_MANGROVE_WOOD -> 10
            Material.STRIPPED_CRIMSON_HYPHAE -> 10
            Material.STRIPPED_WARPED_HYPHAE -> 10
            Material.STRIPPED_BAMBOO_BLOCK -> 10
            Material.OAK_WOOD -> 10
            Material.SPRUCE_WOOD -> 10
            Material.BIRCH_WOOD -> 10
            Material.JUNGLE_WOOD -> 10
            Material.ACACIA_WOOD -> 10
            Material.DARK_OAK_WOOD -> 10
            Material.MANGROVE_WOOD -> 10
            Material.CRIMSON_HYPHAE -> 10
            Material.WARPED_HYPHAE -> 10
            Material.OAK_LEAVES -> 10
            Material.SPRUCE_LEAVES -> 10
            Material.BIRCH_LEAVES -> 10
            Material.JUNGLE_LEAVES -> 10
            Material.ACACIA_LEAVES -> 10
            Material.DARK_OAK_LEAVES -> 10
            Material.MANGROVE_LEAVES -> 10
            Material.AZALEA_LEAVES -> 10
            Material.FLOWERING_AZALEA_LEAVES -> 10
            Material.SPONGE -> 10
            Material.WET_SPONGE -> 10
            Material.GLASS -> 10
            Material.TINTED_GLASS -> 10
            Material.LAPIS_BLOCK -> 10
            Material.SANDSTONE -> 10
            Material.CHISELED_SANDSTONE -> 10
            Material.CUT_SANDSTONE -> 10
            Material.COBWEB -> 10
            Material.GRASS -> 10
            Material.FERN -> 10
            Material.AZALEA -> 10
            Material.FLOWERING_AZALEA -> 10
            Material.DEAD_BUSH -> 10
            Material.SEAGRASS -> 10
            Material.SEA_PICKLE -> 10
            Material.WHITE_WOOL -> 10
            Material.ORANGE_WOOL -> 10
            Material.MAGENTA_WOOL -> 10
            Material.LIGHT_BLUE_WOOL -> 10
            Material.YELLOW_WOOL -> 10
            Material.LIME_WOOL -> 10
            Material.PINK_WOOL -> 10
            Material.GRAY_WOOL -> 10
            Material.LIGHT_GRAY_WOOL -> 10
            Material.CYAN_WOOL -> 10
            Material.PURPLE_WOOL -> 10
            Material.BLUE_WOOL -> 10
            Material.BROWN_WOOL -> 10
            Material.GREEN_WOOL -> 10
            Material.RED_WOOL -> 10
            Material.BLACK_WOOL -> 10
            Material.DANDELION -> 10
            Material.POPPY -> 10
            Material.BLUE_ORCHID -> 10
            Material.ALLIUM -> 10
            Material.AZURE_BLUET -> 10
            Material.RED_TULIP -> 10
            Material.ORANGE_TULIP -> 10
            Material.WHITE_TULIP -> 10
            Material.PINK_TULIP -> 10
            Material.OXEYE_DAISY -> 10
            Material.CORNFLOWER -> 10
            Material.LILY_OF_THE_VALLEY -> 10
            Material.WITHER_ROSE -> 10
            Material.SPORE_BLOSSOM -> 10
            Material.BROWN_MUSHROOM -> 10
            Material.RED_MUSHROOM -> 10
            Material.CRIMSON_FUNGUS -> 10
            Material.WARPED_FUNGUS -> 10
            Material.CRIMSON_ROOTS -> 10
            Material.WARPED_ROOTS -> 10
            Material.NETHER_SPROUTS -> 10
            Material.WEEPING_VINES -> 10
            Material.TWISTING_VINES -> 10
            Material.SUGAR_CANE -> 10
            Material.KELP -> 10
            Material.MOSS_CARPET -> 10
            Material.MOSS_BLOCK -> 10
            Material.HANGING_ROOTS -> 10
            Material.BIG_DRIPLEAF -> 10
            Material.SMALL_DRIPLEAF -> 10
            Material.BAMBOO -> 10
            Material.OAK_SLAB -> 10
            Material.SPRUCE_SLAB -> 10
            Material.BIRCH_SLAB -> 10
            Material.JUNGLE_SLAB -> 10
            Material.ACACIA_SLAB -> 10
            Material.DARK_OAK_SLAB -> 10
            Material.MANGROVE_SLAB -> 10
            Material.BAMBOO_SLAB -> 10
            Material.BAMBOO_MOSAIC_SLAB -> 10
            Material.CRIMSON_SLAB -> 10
            Material.WARPED_SLAB -> 10
            Material.STONE_SLAB -> 10
            Material.SMOOTH_STONE_SLAB -> 10
            Material.SANDSTONE_SLAB -> 10
            Material.CUT_SANDSTONE_SLAB -> 10
            Material.PETRIFIED_OAK_SLAB -> 10
            Material.COBBLESTONE_SLAB -> 10
            Material.BRICK_SLAB -> 10
            Material.STONE_BRICK_SLAB -> 10
            Material.MUD_BRICK_SLAB -> 10
            Material.NETHER_BRICK_SLAB -> 10
            Material.QUARTZ_SLAB -> 10
            Material.RED_SANDSTONE_SLAB -> 10
            Material.CUT_RED_SANDSTONE_SLAB -> 10
            Material.PURPUR_SLAB -> 10
            Material.PRISMARINE_SLAB -> 10
            Material.PRISMARINE_BRICK_SLAB -> 10
            Material.DARK_PRISMARINE_SLAB -> 10
            Material.SMOOTH_QUARTZ -> 10
            Material.SMOOTH_RED_SANDSTONE -> 10
            Material.SMOOTH_SANDSTONE -> 10
            Material.SMOOTH_STONE -> 10
            Material.BRICKS -> 10
            Material.BOOKSHELF -> 10
            Material.CHISELED_BOOKSHELF -> 10
            Material.MOSSY_COBBLESTONE -> 10
            Material.OBSIDIAN -> 10
            Material.TORCH -> 10
            Material.END_ROD -> 10
            Material.CHORUS_PLANT -> 10
            Material.CHORUS_FLOWER -> 10
            Material.PURPUR_BLOCK -> 10
            Material.PURPUR_PILLAR -> 10
            Material.PURPUR_STAIRS -> 10
            Material.SPAWNER -> 10
            Material.CHEST -> 10
            Material.CRAFTING_TABLE -> 10
            Material.FARMLAND -> 10
            Material.FURNACE -> 10
            Material.LADDER -> 10
            Material.COBBLESTONE_STAIRS -> 10
            Material.SNOW -> 10
            Material.ICE -> 10
            Material.SNOW_BLOCK -> 10
            Material.CACTUS -> 10
            Material.CLAY -> 10
            Material.JUKEBOX -> 10
            Material.OAK_FENCE -> 10
            Material.SPRUCE_FENCE -> 10
            Material.BIRCH_FENCE -> 10
            Material.JUNGLE_FENCE -> 10
            Material.ACACIA_FENCE -> 10
            Material.DARK_OAK_FENCE -> 10
            Material.MANGROVE_FENCE -> 10
            Material.BAMBOO_FENCE -> 10
            Material.CRIMSON_FENCE -> 10
            Material.WARPED_FENCE -> 10
            Material.PUMPKIN -> 10
            Material.CARVED_PUMPKIN -> 10
            Material.JACK_O_LANTERN -> 10
            Material.NETHERRACK -> 10
            Material.SOUL_SAND -> 10
            Material.SOUL_SOIL -> 10
            Material.BASALT -> 10
            Material.POLISHED_BASALT -> 10
            Material.SMOOTH_BASALT -> 10
            Material.SOUL_TORCH -> 10
            Material.GLOWSTONE -> 10
            Material.INFESTED_STONE -> 10
            Material.INFESTED_COBBLESTONE -> 10
            Material.INFESTED_STONE_BRICKS -> 10
            Material.INFESTED_MOSSY_STONE_BRICKS -> 10
            Material.INFESTED_CRACKED_STONE_BRICKS -> 10
            Material.INFESTED_CHISELED_STONE_BRICKS -> 10
            Material.INFESTED_DEEPSLATE -> 10
            Material.STONE_BRICKS -> 10
            Material.MOSSY_STONE_BRICKS -> 10
            Material.CRACKED_STONE_BRICKS -> 10
            Material.CHISELED_STONE_BRICKS -> 10
            Material.PACKED_MUD -> 10
            Material.MUD_BRICKS -> 10
            Material.DEEPSLATE_BRICKS -> 10
            Material.CRACKED_DEEPSLATE_BRICKS -> 10
            Material.DEEPSLATE_TILES -> 10
            Material.CRACKED_DEEPSLATE_TILES -> 10
            Material.CHISELED_DEEPSLATE -> 10
            Material.REINFORCED_DEEPSLATE -> 10
            Material.BROWN_MUSHROOM_BLOCK -> 10
            Material.RED_MUSHROOM_BLOCK -> 10
            Material.MUSHROOM_STEM -> 10
            Material.IRON_BARS -> 10
            Material.CHAIN -> 10
            Material.GLASS_PANE -> 10
            Material.MELON -> 10
            Material.VINE -> 10
            Material.GLOW_LICHEN -> 10
            Material.BRICK_STAIRS -> 10
            Material.STONE_BRICK_STAIRS -> 10
            Material.MUD_BRICK_STAIRS -> 10
            Material.MYCELIUM -> 10
            Material.LILY_PAD -> 10
            Material.NETHER_BRICKS -> 10
            Material.CRACKED_NETHER_BRICKS -> 10
            Material.CHISELED_NETHER_BRICKS -> 10
            Material.NETHER_BRICK_FENCE -> 10
            Material.NETHER_BRICK_STAIRS -> 10
            Material.SCULK -> 10
            Material.SCULK_VEIN -> 10
            Material.SCULK_CATALYST -> 10
            Material.SCULK_SHRIEKER -> 10
            Material.ENCHANTING_TABLE -> 10
            Material.END_PORTAL_FRAME -> 10
            Material.END_STONE -> 10
            Material.END_STONE_BRICKS -> 10
            Material.DRAGON_EGG -> 10
            Material.SANDSTONE_STAIRS -> 10
            Material.ENDER_CHEST -> 10
            Material.EMERALD_BLOCK -> 10
            Material.OAK_STAIRS -> 10
            Material.SPRUCE_STAIRS -> 10
            Material.BIRCH_STAIRS -> 10
            Material.JUNGLE_STAIRS -> 10
            Material.ACACIA_STAIRS -> 10
            Material.DARK_OAK_STAIRS -> 10
            Material.MANGROVE_STAIRS -> 10
            Material.BAMBOO_STAIRS -> 10
            Material.BAMBOO_MOSAIC_STAIRS -> 10
            Material.CRIMSON_STAIRS -> 10
            Material.WARPED_STAIRS -> 10
            Material.COMMAND_BLOCK -> 10
            Material.BEACON -> 10
            Material.COBBLESTONE_WALL -> 10
            Material.MOSSY_COBBLESTONE_WALL -> 10
            Material.BRICK_WALL -> 10
            Material.PRISMARINE_WALL -> 10
            Material.RED_SANDSTONE_WALL -> 10
            Material.MOSSY_STONE_BRICK_WALL -> 10
            Material.GRANITE_WALL -> 10
            Material.STONE_BRICK_WALL -> 10
            Material.MUD_BRICK_WALL -> 10
            Material.NETHER_BRICK_WALL -> 10
            Material.ANDESITE_WALL -> 10
            Material.RED_NETHER_BRICK_WALL -> 10
            Material.SANDSTONE_WALL -> 10
            Material.END_STONE_BRICK_WALL -> 10
            Material.DIORITE_WALL -> 10
            Material.BLACKSTONE_WALL -> 10
            Material.POLISHED_BLACKSTONE_WALL -> 10
            Material.POLISHED_BLACKSTONE_BRICK_WALL -> 10
            Material.COBBLED_DEEPSLATE_WALL -> 10
            Material.POLISHED_DEEPSLATE_WALL -> 10
            Material.DEEPSLATE_BRICK_WALL -> 10
            Material.DEEPSLATE_TILE_WALL -> 10
            Material.ANVIL -> 10
            Material.CHIPPED_ANVIL -> 10
            Material.DAMAGED_ANVIL -> 10
            Material.CHISELED_QUARTZ_BLOCK -> 10
            Material.QUARTZ_BLOCK -> 10
            Material.QUARTZ_BRICKS -> 10
            Material.QUARTZ_PILLAR -> 10
            Material.QUARTZ_STAIRS -> 10
            Material.WHITE_TERRACOTTA -> 10
            Material.ORANGE_TERRACOTTA -> 10
            Material.MAGENTA_TERRACOTTA -> 10
            Material.LIGHT_BLUE_TERRACOTTA -> 10
            Material.YELLOW_TERRACOTTA -> 10
            Material.LIME_TERRACOTTA -> 10
            Material.PINK_TERRACOTTA -> 10
            Material.GRAY_TERRACOTTA -> 10
            Material.LIGHT_GRAY_TERRACOTTA -> 10
            Material.CYAN_TERRACOTTA -> 10
            Material.PURPLE_TERRACOTTA -> 10
            Material.BLUE_TERRACOTTA -> 10
            Material.BROWN_TERRACOTTA -> 10
            Material.GREEN_TERRACOTTA -> 10
            Material.RED_TERRACOTTA -> 10
            Material.BLACK_TERRACOTTA -> 10
            Material.BARRIER -> 10
            Material.LIGHT -> 10
            Material.HAY_BLOCK -> 10
            Material.WHITE_CARPET -> 10
            Material.ORANGE_CARPET -> 10
            Material.MAGENTA_CARPET -> 10
            Material.LIGHT_BLUE_CARPET -> 10
            Material.YELLOW_CARPET -> 10
            Material.LIME_CARPET -> 10
            Material.PINK_CARPET -> 10
            Material.GRAY_CARPET -> 10
            Material.LIGHT_GRAY_CARPET -> 10
            Material.CYAN_CARPET -> 10
            Material.PURPLE_CARPET -> 10
            Material.BLUE_CARPET -> 10
            Material.BROWN_CARPET -> 10
            Material.GREEN_CARPET -> 10
            Material.RED_CARPET -> 10
            Material.BLACK_CARPET -> 10
            Material.TERRACOTTA -> 10
            Material.PACKED_ICE -> 10
            Material.DIRT_PATH -> 10
            Material.SUNFLOWER -> 10
            Material.LILAC -> 10
            Material.ROSE_BUSH -> 10
            Material.PEONY -> 10
            Material.TALL_GRASS -> 10
            Material.LARGE_FERN -> 10
            Material.WHITE_STAINED_GLASS -> 10
            Material.ORANGE_STAINED_GLASS -> 10
            Material.MAGENTA_STAINED_GLASS -> 10
            Material.LIGHT_BLUE_STAINED_GLASS -> 10
            Material.YELLOW_STAINED_GLASS -> 10
            Material.LIME_STAINED_GLASS -> 10
            Material.PINK_STAINED_GLASS -> 10
            Material.GRAY_STAINED_GLASS -> 10
            Material.LIGHT_GRAY_STAINED_GLASS -> 10
            Material.CYAN_STAINED_GLASS -> 10
            Material.PURPLE_STAINED_GLASS -> 10
            Material.BLUE_STAINED_GLASS -> 10
            Material.BROWN_STAINED_GLASS -> 10
            Material.GREEN_STAINED_GLASS -> 10
            Material.RED_STAINED_GLASS -> 10
            Material.BLACK_STAINED_GLASS -> 10
            Material.WHITE_STAINED_GLASS_PANE -> 10
            Material.ORANGE_STAINED_GLASS_PANE -> 10
            Material.MAGENTA_STAINED_GLASS_PANE -> 10
            Material.LIGHT_BLUE_STAINED_GLASS_PANE -> 10
            Material.YELLOW_STAINED_GLASS_PANE -> 10
            Material.LIME_STAINED_GLASS_PANE -> 10
            Material.PINK_STAINED_GLASS_PANE -> 10
            Material.GRAY_STAINED_GLASS_PANE -> 10
            Material.LIGHT_GRAY_STAINED_GLASS_PANE -> 10
            Material.CYAN_STAINED_GLASS_PANE -> 10
            Material.PURPLE_STAINED_GLASS_PANE -> 10
            Material.BLUE_STAINED_GLASS_PANE -> 10
            Material.BROWN_STAINED_GLASS_PANE -> 10
            Material.GREEN_STAINED_GLASS_PANE -> 10
            Material.RED_STAINED_GLASS_PANE -> 10
            Material.BLACK_STAINED_GLASS_PANE -> 10
            Material.PRISMARINE -> 10
            Material.PRISMARINE_BRICKS -> 10
            Material.DARK_PRISMARINE -> 10
            Material.PRISMARINE_STAIRS -> 10
            Material.PRISMARINE_BRICK_STAIRS -> 10
            Material.DARK_PRISMARINE_STAIRS -> 10
            Material.SEA_LANTERN -> 10
            Material.RED_SANDSTONE -> 10
            Material.CHISELED_RED_SANDSTONE -> 10
            Material.CUT_RED_SANDSTONE -> 10
            Material.RED_SANDSTONE_STAIRS -> 10
            Material.REPEATING_COMMAND_BLOCK -> 10
            Material.CHAIN_COMMAND_BLOCK -> 10
            Material.MAGMA_BLOCK -> 10
            Material.NETHER_WART_BLOCK -> 10
            Material.WARPED_WART_BLOCK -> 10
            Material.RED_NETHER_BRICKS -> 10
            Material.BONE_BLOCK -> 10
            Material.STRUCTURE_VOID -> 10
            Material.SHULKER_BOX -> 10
            Material.WHITE_SHULKER_BOX -> 10
            Material.ORANGE_SHULKER_BOX -> 10
            Material.MAGENTA_SHULKER_BOX -> 10
            Material.LIGHT_BLUE_SHULKER_BOX -> 10
            Material.YELLOW_SHULKER_BOX -> 10
            Material.LIME_SHULKER_BOX -> 10
            Material.PINK_SHULKER_BOX -> 10
            Material.GRAY_SHULKER_BOX -> 10
            Material.LIGHT_GRAY_SHULKER_BOX -> 10
            Material.CYAN_SHULKER_BOX -> 10
            Material.PURPLE_SHULKER_BOX -> 10
            Material.BLUE_SHULKER_BOX -> 10
            Material.BROWN_SHULKER_BOX -> 10
            Material.GREEN_SHULKER_BOX -> 10
            Material.RED_SHULKER_BOX -> 10
            Material.BLACK_SHULKER_BOX -> 10
            Material.WHITE_GLAZED_TERRACOTTA -> 10
            Material.ORANGE_GLAZED_TERRACOTTA -> 10
            Material.MAGENTA_GLAZED_TERRACOTTA -> 10
            Material.LIGHT_BLUE_GLAZED_TERRACOTTA -> 10
            Material.YELLOW_GLAZED_TERRACOTTA -> 10
            Material.LIME_GLAZED_TERRACOTTA -> 10
            Material.PINK_GLAZED_TERRACOTTA -> 10
            Material.GRAY_GLAZED_TERRACOTTA -> 10
            Material.LIGHT_GRAY_GLAZED_TERRACOTTA -> 10
            Material.CYAN_GLAZED_TERRACOTTA -> 10
            Material.PURPLE_GLAZED_TERRACOTTA -> 10
            Material.BLUE_GLAZED_TERRACOTTA -> 10
            Material.BROWN_GLAZED_TERRACOTTA -> 10
            Material.GREEN_GLAZED_TERRACOTTA -> 10
            Material.RED_GLAZED_TERRACOTTA -> 10
            Material.BLACK_GLAZED_TERRACOTTA -> 10
            Material.WHITE_CONCRETE -> 10
            Material.ORANGE_CONCRETE -> 10
            Material.MAGENTA_CONCRETE -> 10
            Material.LIGHT_BLUE_CONCRETE -> 10
            Material.YELLOW_CONCRETE -> 10
            Material.LIME_CONCRETE -> 10
            Material.PINK_CONCRETE -> 10
            Material.GRAY_CONCRETE -> 10
            Material.LIGHT_GRAY_CONCRETE -> 10
            Material.CYAN_CONCRETE -> 10
            Material.PURPLE_CONCRETE -> 10
            Material.BLUE_CONCRETE -> 10
            Material.BROWN_CONCRETE -> 10
            Material.GREEN_CONCRETE -> 10
            Material.RED_CONCRETE -> 10
            Material.BLACK_CONCRETE -> 10
            Material.WHITE_CONCRETE_POWDER -> 10
            Material.ORANGE_CONCRETE_POWDER -> 10
            Material.MAGENTA_CONCRETE_POWDER -> 10
            Material.LIGHT_BLUE_CONCRETE_POWDER -> 10
            Material.YELLOW_CONCRETE_POWDER -> 10
            Material.LIME_CONCRETE_POWDER -> 10
            Material.PINK_CONCRETE_POWDER -> 10
            Material.GRAY_CONCRETE_POWDER -> 10
            Material.LIGHT_GRAY_CONCRETE_POWDER -> 10
            Material.CYAN_CONCRETE_POWDER -> 10
            Material.PURPLE_CONCRETE_POWDER -> 10
            Material.BLUE_CONCRETE_POWDER -> 10
            Material.BROWN_CONCRETE_POWDER -> 10
            Material.GREEN_CONCRETE_POWDER -> 10
            Material.RED_CONCRETE_POWDER -> 10
            Material.BLACK_CONCRETE_POWDER -> 10
            Material.TURTLE_EGG -> 10
            Material.DEAD_TUBE_CORAL_BLOCK -> 10
            Material.DEAD_BRAIN_CORAL_BLOCK -> 10
            Material.DEAD_BUBBLE_CORAL_BLOCK -> 10
            Material.DEAD_FIRE_CORAL_BLOCK -> 10
            Material.DEAD_HORN_CORAL_BLOCK -> 10
            Material.TUBE_CORAL_BLOCK -> 10
            Material.BRAIN_CORAL_BLOCK -> 10
            Material.BUBBLE_CORAL_BLOCK -> 10
            Material.FIRE_CORAL_BLOCK -> 10
            Material.HORN_CORAL_BLOCK -> 10
            Material.TUBE_CORAL -> 10
            Material.BRAIN_CORAL -> 10
            Material.BUBBLE_CORAL -> 10
            Material.FIRE_CORAL -> 10
            Material.HORN_CORAL -> 10
            Material.DEAD_BRAIN_CORAL -> 10
            Material.DEAD_BUBBLE_CORAL -> 10
            Material.DEAD_FIRE_CORAL -> 10
            Material.DEAD_HORN_CORAL -> 10
            Material.DEAD_TUBE_CORAL -> 10
            Material.TUBE_CORAL_FAN -> 10
            Material.BRAIN_CORAL_FAN -> 10
            Material.BUBBLE_CORAL_FAN -> 10
            Material.FIRE_CORAL_FAN -> 10
            Material.HORN_CORAL_FAN -> 10
            Material.DEAD_TUBE_CORAL_FAN -> 10
            Material.DEAD_BRAIN_CORAL_FAN -> 10
            Material.DEAD_BUBBLE_CORAL_FAN -> 10
            Material.DEAD_FIRE_CORAL_FAN -> 10
            Material.DEAD_HORN_CORAL_FAN -> 10
            Material.BLUE_ICE -> 10
            Material.CONDUIT -> 10
            Material.POLISHED_GRANITE_STAIRS -> 10
            Material.SMOOTH_RED_SANDSTONE_STAIRS -> 10
            Material.MOSSY_STONE_BRICK_STAIRS -> 10
            Material.POLISHED_DIORITE_STAIRS -> 10
            Material.MOSSY_COBBLESTONE_STAIRS -> 10
            Material.END_STONE_BRICK_STAIRS -> 10
            Material.STONE_STAIRS -> 10
            Material.SMOOTH_SANDSTONE_STAIRS -> 10
            Material.SMOOTH_QUARTZ_STAIRS -> 10
            Material.GRANITE_STAIRS -> 10
            Material.ANDESITE_STAIRS -> 10
            Material.RED_NETHER_BRICK_STAIRS -> 10
            Material.POLISHED_ANDESITE_STAIRS -> 10
            Material.DIORITE_STAIRS -> 10
            Material.COBBLED_DEEPSLATE_STAIRS -> 10
            Material.POLISHED_DEEPSLATE_STAIRS -> 10
            Material.DEEPSLATE_BRICK_STAIRS -> 10
            Material.DEEPSLATE_TILE_STAIRS -> 10
            Material.POLISHED_GRANITE_SLAB -> 10
            Material.SMOOTH_RED_SANDSTONE_SLAB -> 10
            Material.MOSSY_STONE_BRICK_SLAB -> 10
            Material.POLISHED_DIORITE_SLAB -> 10
            Material.MOSSY_COBBLESTONE_SLAB -> 10
            Material.END_STONE_BRICK_SLAB -> 10
            Material.SMOOTH_SANDSTONE_SLAB -> 10
            Material.SMOOTH_QUARTZ_SLAB -> 10
            Material.GRANITE_SLAB -> 10
            Material.ANDESITE_SLAB -> 10
            Material.RED_NETHER_BRICK_SLAB -> 10
            Material.POLISHED_ANDESITE_SLAB -> 10
            Material.DIORITE_SLAB -> 10
            Material.COBBLED_DEEPSLATE_SLAB -> 10
            Material.POLISHED_DEEPSLATE_SLAB -> 10
            Material.DEEPSLATE_BRICK_SLAB -> 10
            Material.DEEPSLATE_TILE_SLAB -> 10
            Material.SCAFFOLDING -> 10
            Material.REDSTONE -> 10
            Material.REDSTONE_TORCH -> 10
            Material.REDSTONE_BLOCK -> 10
            Material.REPEATER -> 10
            Material.COMPARATOR -> 10
            Material.PISTON -> 10
            Material.STICKY_PISTON -> 10
            Material.SLIME_BLOCK -> 10
            Material.HONEY_BLOCK -> 10
            Material.OBSERVER -> 10
            Material.HOPPER -> 10
            Material.DISPENSER -> 10
            Material.DROPPER -> 10
            Material.LECTERN -> 10
            Material.TARGET -> 10
            Material.LEVER -> 10
            Material.LIGHTNING_ROD -> 10
            Material.DAYLIGHT_DETECTOR -> 10
            Material.SCULK_SENSOR -> 10
            Material.TRIPWIRE_HOOK -> 10
            Material.TRAPPED_CHEST -> 10
            Material.TNT -> 10
            Material.REDSTONE_LAMP -> 10
            Material.NOTE_BLOCK -> 10
            Material.STONE_BUTTON -> 10
            Material.POLISHED_BLACKSTONE_BUTTON -> 10
            Material.OAK_BUTTON -> 10
            Material.SPRUCE_BUTTON -> 10
            Material.BIRCH_BUTTON -> 10
            Material.JUNGLE_BUTTON -> 10
            Material.ACACIA_BUTTON -> 10
            Material.DARK_OAK_BUTTON -> 10
            Material.MANGROVE_BUTTON -> 10
            Material.BAMBOO_BUTTON -> 10
            Material.CRIMSON_BUTTON -> 10
            Material.WARPED_BUTTON -> 10
            Material.STONE_PRESSURE_PLATE -> 10
            Material.POLISHED_BLACKSTONE_PRESSURE_PLATE -> 10
            Material.LIGHT_WEIGHTED_PRESSURE_PLATE -> 10
            Material.HEAVY_WEIGHTED_PRESSURE_PLATE -> 10
            Material.OAK_PRESSURE_PLATE -> 10
            Material.SPRUCE_PRESSURE_PLATE -> 10
            Material.BIRCH_PRESSURE_PLATE -> 10
            Material.JUNGLE_PRESSURE_PLATE -> 10
            Material.ACACIA_PRESSURE_PLATE -> 10
            Material.DARK_OAK_PRESSURE_PLATE -> 10
            Material.MANGROVE_PRESSURE_PLATE -> 10
            Material.BAMBOO_PRESSURE_PLATE -> 10
            Material.CRIMSON_PRESSURE_PLATE -> 10
            Material.WARPED_PRESSURE_PLATE -> 10
            Material.IRON_DOOR -> 10
            Material.OAK_DOOR -> 10
            Material.SPRUCE_DOOR -> 10
            Material.BIRCH_DOOR -> 10
            Material.JUNGLE_DOOR -> 10
            Material.ACACIA_DOOR -> 10
            Material.DARK_OAK_DOOR -> 10
            Material.MANGROVE_DOOR -> 10
            Material.BAMBOO_DOOR -> 10
            Material.CRIMSON_DOOR -> 10
            Material.WARPED_DOOR -> 10
            Material.IRON_TRAPDOOR -> 10
            Material.OAK_TRAPDOOR -> 10
            Material.SPRUCE_TRAPDOOR -> 10
            Material.BIRCH_TRAPDOOR -> 10
            Material.JUNGLE_TRAPDOOR -> 10
            Material.ACACIA_TRAPDOOR -> 10
            Material.DARK_OAK_TRAPDOOR -> 10
            Material.MANGROVE_TRAPDOOR -> 10
            Material.BAMBOO_TRAPDOOR -> 10
            Material.CRIMSON_TRAPDOOR -> 10
            Material.WARPED_TRAPDOOR -> 10
            Material.OAK_FENCE_GATE -> 10
            Material.SPRUCE_FENCE_GATE -> 10
            Material.BIRCH_FENCE_GATE -> 10
            Material.JUNGLE_FENCE_GATE -> 10
            Material.ACACIA_FENCE_GATE -> 10
            Material.DARK_OAK_FENCE_GATE -> 10
            Material.MANGROVE_FENCE_GATE -> 10
            Material.BAMBOO_FENCE_GATE -> 10
            Material.CRIMSON_FENCE_GATE -> 10
            Material.WARPED_FENCE_GATE -> 10
            Material.POWERED_RAIL -> 10
            Material.DETECTOR_RAIL -> 10
            Material.RAIL -> 10
            Material.ACTIVATOR_RAIL -> 10
            Material.SADDLE -> 10
            Material.MINECART -> 10
            Material.CHEST_MINECART -> 10
            Material.FURNACE_MINECART -> 10
            Material.TNT_MINECART -> 10
            Material.HOPPER_MINECART -> 10
            Material.CARROT_ON_A_STICK -> 10
            Material.WARPED_FUNGUS_ON_A_STICK -> 10
            Material.ELYTRA -> 10
            Material.OAK_BOAT -> 10
            Material.OAK_CHEST_BOAT -> 10
            Material.SPRUCE_BOAT -> 10
            Material.SPRUCE_CHEST_BOAT -> 10
            Material.BIRCH_BOAT -> 10
            Material.BIRCH_CHEST_BOAT -> 10
            Material.JUNGLE_BOAT -> 10
            Material.JUNGLE_CHEST_BOAT -> 10
            Material.ACACIA_BOAT -> 10
            Material.ACACIA_CHEST_BOAT -> 10
            Material.DARK_OAK_BOAT -> 10
            Material.DARK_OAK_CHEST_BOAT -> 10
            Material.MANGROVE_BOAT -> 10
            Material.MANGROVE_CHEST_BOAT -> 10
            Material.BAMBOO_RAFT -> 10
            Material.BAMBOO_CHEST_RAFT -> 10
            Material.STRUCTURE_BLOCK -> 10
            Material.JIGSAW -> 10
            Material.TURTLE_HELMET -> 10
            Material.SCUTE -> 10
            Material.FLINT_AND_STEEL -> 10
            Material.APPLE -> 10
            Material.BOW -> 10
            Material.ARROW -> 10
            Material.COAL -> 10
            Material.CHARCOAL -> 10
            Material.DIAMOND -> 10
            Material.EMERALD -> 10
            Material.LAPIS_LAZULI -> 10
            Material.QUARTZ -> 10
            Material.AMETHYST_SHARD -> 10
            Material.RAW_IRON -> 10
            Material.IRON_INGOT -> 10
            Material.RAW_COPPER -> 10
            Material.COPPER_INGOT -> 10
            Material.RAW_GOLD -> 10
            Material.GOLD_INGOT -> 10
            Material.NETHERITE_INGOT -> 10
            Material.NETHERITE_SCRAP -> 10
            Material.WOODEN_SWORD -> 10
            Material.WOODEN_SHOVEL -> 10
            Material.WOODEN_PICKAXE -> 10
            Material.WOODEN_AXE -> 10
            Material.WOODEN_HOE -> 10
            Material.STONE_SWORD -> 10
            Material.STONE_SHOVEL -> 10
            Material.STONE_PICKAXE -> 10
            Material.STONE_AXE -> 10
            Material.STONE_HOE -> 10
            Material.GOLDEN_SWORD -> 10
            Material.GOLDEN_SHOVEL -> 10
            Material.GOLDEN_PICKAXE -> 10
            Material.GOLDEN_AXE -> 10
            Material.GOLDEN_HOE -> 10
            Material.IRON_SWORD -> 10
            Material.IRON_SHOVEL -> 10
            Material.IRON_PICKAXE -> 10
            Material.IRON_AXE -> 10
            Material.IRON_HOE -> 10
            Material.DIAMOND_SWORD -> 10
            Material.DIAMOND_SHOVEL -> 10
            Material.DIAMOND_PICKAXE -> 10
            Material.DIAMOND_AXE -> 10
            Material.DIAMOND_HOE -> 10
            Material.NETHERITE_SWORD -> 10
            Material.NETHERITE_SHOVEL -> 10
            Material.NETHERITE_PICKAXE -> 10
            Material.NETHERITE_AXE -> 10
            Material.NETHERITE_HOE -> 10
            Material.STICK -> 10
            Material.BOWL -> 10
            Material.MUSHROOM_STEW -> 10
            Material.STRING -> 10
            Material.FEATHER -> 10
            Material.GUNPOWDER -> 10
            Material.WHEAT_SEEDS -> 10
            Material.WHEAT -> 10
            Material.BREAD -> 10
            Material.LEATHER_HELMET -> 10
            Material.LEATHER_CHESTPLATE -> 10
            Material.LEATHER_LEGGINGS -> 10
            Material.LEATHER_BOOTS -> 10
            Material.CHAINMAIL_HELMET -> 10
            Material.CHAINMAIL_CHESTPLATE -> 10
            Material.CHAINMAIL_LEGGINGS -> 10
            Material.CHAINMAIL_BOOTS -> 10
            Material.IRON_HELMET -> 10
            Material.IRON_CHESTPLATE -> 10
            Material.IRON_LEGGINGS -> 10
            Material.IRON_BOOTS -> 10
            Material.DIAMOND_HELMET -> 10
            Material.DIAMOND_CHESTPLATE -> 10
            Material.DIAMOND_LEGGINGS -> 10
            Material.DIAMOND_BOOTS -> 10
            Material.GOLDEN_HELMET -> 10
            Material.GOLDEN_CHESTPLATE -> 10
            Material.GOLDEN_LEGGINGS -> 10
            Material.GOLDEN_BOOTS -> 10
            Material.NETHERITE_HELMET -> 10
            Material.NETHERITE_CHESTPLATE -> 10
            Material.NETHERITE_LEGGINGS -> 10
            Material.NETHERITE_BOOTS -> 10
            Material.FLINT -> 10
            Material.PORKCHOP -> 10
            Material.COOKED_PORKCHOP -> 10
            Material.PAINTING -> 10
            Material.GOLDEN_APPLE -> 10
            Material.ENCHANTED_GOLDEN_APPLE -> 10
            Material.OAK_SIGN -> 10
            Material.SPRUCE_SIGN -> 10
            Material.BIRCH_SIGN -> 10
            Material.JUNGLE_SIGN -> 10
            Material.ACACIA_SIGN -> 10
            Material.DARK_OAK_SIGN -> 10
            Material.MANGROVE_SIGN -> 10
            Material.BAMBOO_SIGN -> 10
            Material.CRIMSON_SIGN -> 10
            Material.WARPED_SIGN -> 10
            Material.OAK_HANGING_SIGN -> 10
            Material.SPRUCE_HANGING_SIGN -> 10
            Material.BIRCH_HANGING_SIGN -> 10
            Material.JUNGLE_HANGING_SIGN -> 10
            Material.ACACIA_HANGING_SIGN -> 10
            Material.DARK_OAK_HANGING_SIGN -> 10
            Material.MANGROVE_HANGING_SIGN -> 10
            Material.BAMBOO_HANGING_SIGN -> 10
            Material.CRIMSON_HANGING_SIGN -> 10
            Material.WARPED_HANGING_SIGN -> 10
            Material.BUCKET -> 10
            Material.WATER_BUCKET -> 10
            Material.LAVA_BUCKET -> 10
            Material.POWDER_SNOW_BUCKET -> 10
            Material.SNOWBALL -> 10
            Material.LEATHER -> 10
            Material.MILK_BUCKET -> 10
            Material.PUFFERFISH_BUCKET -> 10
            Material.SALMON_BUCKET -> 10
            Material.COD_BUCKET -> 10
            Material.TROPICAL_FISH_BUCKET -> 10
            Material.AXOLOTL_BUCKET -> 10
            Material.TADPOLE_BUCKET -> 10
            Material.BRICK -> 10
            Material.CLAY_BALL -> 10
            Material.DRIED_KELP_BLOCK -> 10
            Material.PAPER -> 10
            Material.BOOK -> 10
            Material.SLIME_BALL -> 10
            Material.EGG -> 10
            Material.COMPASS -> 10
            Material.RECOVERY_COMPASS -> 10
            Material.BUNDLE -> 10
            Material.FISHING_ROD -> 10
            Material.CLOCK -> 10
            Material.SPYGLASS -> 10
            Material.GLOWSTONE_DUST -> 10
            Material.COD -> 10
            Material.SALMON -> 10
            Material.TROPICAL_FISH -> 10
            Material.PUFFERFISH -> 10
            Material.COOKED_COD -> 10
            Material.COOKED_SALMON -> 10
            Material.INK_SAC -> 10
            Material.GLOW_INK_SAC -> 10
            Material.COCOA_BEANS -> 10
            Material.WHITE_DYE -> 10
            Material.ORANGE_DYE -> 10
            Material.MAGENTA_DYE -> 10
            Material.LIGHT_BLUE_DYE -> 10
            Material.YELLOW_DYE -> 10
            Material.LIME_DYE -> 10
            Material.PINK_DYE -> 10
            Material.GRAY_DYE -> 10
            Material.LIGHT_GRAY_DYE -> 10
            Material.CYAN_DYE -> 10
            Material.PURPLE_DYE -> 10
            Material.BLUE_DYE -> 10
            Material.BROWN_DYE -> 10
            Material.GREEN_DYE -> 10
            Material.RED_DYE -> 10
            Material.BLACK_DYE -> 10
            Material.BONE_MEAL -> 10
            Material.BONE -> 10
            Material.SUGAR -> 10
            Material.CAKE -> 10
            Material.WHITE_BED -> 10
            Material.ORANGE_BED -> 10
            Material.MAGENTA_BED -> 10
            Material.LIGHT_BLUE_BED -> 10
            Material.YELLOW_BED -> 10
            Material.LIME_BED -> 10
            Material.PINK_BED -> 10
            Material.GRAY_BED -> 10
            Material.LIGHT_GRAY_BED -> 10
            Material.CYAN_BED -> 10
            Material.PURPLE_BED -> 10
            Material.BLUE_BED -> 10
            Material.BROWN_BED -> 10
            Material.GREEN_BED -> 10
            Material.RED_BED -> 10
            Material.BLACK_BED -> 10
            Material.COOKIE -> 10
            Material.FILLED_MAP -> 10
            Material.SHEARS -> 10
            Material.MELON_SLICE -> 10
            Material.DRIED_KELP -> 10
            Material.PUMPKIN_SEEDS -> 10
            Material.MELON_SEEDS -> 10
            Material.BEEF -> 10
            Material.COOKED_BEEF -> 10
            Material.CHICKEN -> 10
            Material.COOKED_CHICKEN -> 10
            Material.ROTTEN_FLESH -> 10
            Material.ENDER_PEARL -> 10
            Material.BLAZE_ROD -> 10
            Material.GHAST_TEAR -> 10
            Material.GOLD_NUGGET -> 10
            Material.NETHER_WART -> 10
            Material.POTION -> 10
            Material.GLASS_BOTTLE -> 10
            Material.SPIDER_EYE -> 10
            Material.FERMENTED_SPIDER_EYE -> 10
            Material.BLAZE_POWDER -> 10
            Material.MAGMA_CREAM -> 10
            Material.BREWING_STAND -> 10
            Material.CAULDRON -> 10
            Material.ENDER_EYE -> 10
            Material.GLISTERING_MELON_SLICE -> 10
            Material.ALLAY_SPAWN_EGG -> 10
            Material.AXOLOTL_SPAWN_EGG -> 10
            Material.BAT_SPAWN_EGG -> 10
            Material.BEE_SPAWN_EGG -> 10
            Material.BLAZE_SPAWN_EGG -> 10
            Material.CAT_SPAWN_EGG -> 10
            Material.CAMEL_SPAWN_EGG -> 10
            Material.CAVE_SPIDER_SPAWN_EGG -> 10
            Material.CHICKEN_SPAWN_EGG -> 10
            Material.COD_SPAWN_EGG -> 10
            Material.COW_SPAWN_EGG -> 10
            Material.CREEPER_SPAWN_EGG -> 10
            Material.DOLPHIN_SPAWN_EGG -> 10
            Material.DONKEY_SPAWN_EGG -> 10
            Material.DROWNED_SPAWN_EGG -> 10
            Material.ELDER_GUARDIAN_SPAWN_EGG -> 10
            Material.ENDER_DRAGON_SPAWN_EGG -> 10
            Material.ENDERMAN_SPAWN_EGG -> 10
            Material.ENDERMITE_SPAWN_EGG -> 10
            Material.EVOKER_SPAWN_EGG -> 10
            Material.FOX_SPAWN_EGG -> 10
            Material.FROG_SPAWN_EGG -> 10
            Material.GHAST_SPAWN_EGG -> 10
            Material.GLOW_SQUID_SPAWN_EGG -> 10
            Material.GOAT_SPAWN_EGG -> 10
            Material.GUARDIAN_SPAWN_EGG -> 10
            Material.HOGLIN_SPAWN_EGG -> 10
            Material.HORSE_SPAWN_EGG -> 10
            Material.HUSK_SPAWN_EGG -> 10
            Material.IRON_GOLEM_SPAWN_EGG -> 10
            Material.LLAMA_SPAWN_EGG -> 10
            Material.MAGMA_CUBE_SPAWN_EGG -> 10
            Material.MOOSHROOM_SPAWN_EGG -> 10
            Material.MULE_SPAWN_EGG -> 10
            Material.OCELOT_SPAWN_EGG -> 10
            Material.PANDA_SPAWN_EGG -> 10
            Material.PARROT_SPAWN_EGG -> 10
            Material.PHANTOM_SPAWN_EGG -> 10
            Material.PIG_SPAWN_EGG -> 10
            Material.PIGLIN_SPAWN_EGG -> 10
            Material.PIGLIN_BRUTE_SPAWN_EGG -> 10
            Material.PILLAGER_SPAWN_EGG -> 10
            Material.POLAR_BEAR_SPAWN_EGG -> 10
            Material.PUFFERFISH_SPAWN_EGG -> 10
            Material.RABBIT_SPAWN_EGG -> 10
            Material.RAVAGER_SPAWN_EGG -> 10
            Material.SALMON_SPAWN_EGG -> 10
            Material.SHEEP_SPAWN_EGG -> 10
            Material.SHULKER_SPAWN_EGG -> 10
            Material.SILVERFISH_SPAWN_EGG -> 10
            Material.SKELETON_SPAWN_EGG -> 10
            Material.SKELETON_HORSE_SPAWN_EGG -> 10
            Material.SLIME_SPAWN_EGG -> 10
            Material.SNOW_GOLEM_SPAWN_EGG -> 10
            Material.SPIDER_SPAWN_EGG -> 10
            Material.SQUID_SPAWN_EGG -> 10
            Material.STRAY_SPAWN_EGG -> 10
            Material.STRIDER_SPAWN_EGG -> 10
            Material.TADPOLE_SPAWN_EGG -> 10
            Material.TRADER_LLAMA_SPAWN_EGG -> 10
            Material.TROPICAL_FISH_SPAWN_EGG -> 10
            Material.TURTLE_SPAWN_EGG -> 10
            Material.VEX_SPAWN_EGG -> 10
            Material.VILLAGER_SPAWN_EGG -> 10
            Material.VINDICATOR_SPAWN_EGG -> 10
            Material.WANDERING_TRADER_SPAWN_EGG -> 10
            Material.WARDEN_SPAWN_EGG -> 10
            Material.WITCH_SPAWN_EGG -> 10
            Material.WITHER_SPAWN_EGG -> 10
            Material.WITHER_SKELETON_SPAWN_EGG -> 10
            Material.WOLF_SPAWN_EGG -> 10
            Material.ZOGLIN_SPAWN_EGG -> 10
            Material.ZOMBIE_SPAWN_EGG -> 10
            Material.ZOMBIE_HORSE_SPAWN_EGG -> 10
            Material.ZOMBIE_VILLAGER_SPAWN_EGG -> 10
            Material.ZOMBIFIED_PIGLIN_SPAWN_EGG -> 10
            Material.EXPERIENCE_BOTTLE -> 10
            Material.FIRE_CHARGE -> 10
            Material.WRITABLE_BOOK -> 10
            Material.WRITTEN_BOOK -> 10
            Material.ITEM_FRAME -> 10
            Material.GLOW_ITEM_FRAME -> 10
            Material.FLOWER_POT -> 10
            Material.CARROT -> 10
            Material.POTATO -> 10
            Material.BAKED_POTATO -> 10
            Material.POISONOUS_POTATO -> 10
            Material.MAP -> 10
            Material.GOLDEN_CARROT -> 10
            Material.SKELETON_SKULL -> 10
            Material.WITHER_SKELETON_SKULL -> 10
            Material.PLAYER_HEAD -> 10
            Material.ZOMBIE_HEAD -> 10
            Material.CREEPER_HEAD -> 10
            Material.DRAGON_HEAD -> 10
            Material.PIGLIN_HEAD -> 10
            Material.NETHER_STAR -> 10
            Material.PUMPKIN_PIE -> 10
            Material.FIREWORK_ROCKET -> 10
            Material.FIREWORK_STAR -> 10
            Material.ENCHANTED_BOOK -> 10
            Material.NETHER_BRICK -> 10
            Material.PRISMARINE_SHARD -> 10
            Material.PRISMARINE_CRYSTALS -> 10
            Material.RABBIT -> 10
            Material.COOKED_RABBIT -> 10
            Material.RABBIT_STEW -> 10
            Material.RABBIT_FOOT -> 10
            Material.RABBIT_HIDE -> 10
            Material.ARMOR_STAND -> 10
            Material.IRON_HORSE_ARMOR -> 10
            Material.GOLDEN_HORSE_ARMOR -> 10
            Material.DIAMOND_HORSE_ARMOR -> 10
            Material.LEATHER_HORSE_ARMOR -> 10
            Material.LEAD -> 10
            Material.NAME_TAG -> 10
            Material.COMMAND_BLOCK_MINECART -> 10
            Material.MUTTON -> 10
            Material.COOKED_MUTTON -> 10
            Material.WHITE_BANNER -> 10
            Material.ORANGE_BANNER -> 10
            Material.MAGENTA_BANNER -> 10
            Material.LIGHT_BLUE_BANNER -> 10
            Material.YELLOW_BANNER -> 10
            Material.LIME_BANNER -> 10
            Material.PINK_BANNER -> 10
            Material.GRAY_BANNER -> 10
            Material.LIGHT_GRAY_BANNER -> 10
            Material.CYAN_BANNER -> 10
            Material.PURPLE_BANNER -> 10
            Material.BLUE_BANNER -> 10
            Material.BROWN_BANNER -> 10
            Material.GREEN_BANNER -> 10
            Material.RED_BANNER -> 10
            Material.BLACK_BANNER -> 10
            Material.END_CRYSTAL -> 10
            Material.CHORUS_FRUIT -> 10
            Material.POPPED_CHORUS_FRUIT -> 10
            Material.BEETROOT -> 10
            Material.BEETROOT_SEEDS -> 10
            Material.BEETROOT_SOUP -> 10
            Material.DRAGON_BREATH -> 10
            Material.SPLASH_POTION -> 10
            Material.SPECTRAL_ARROW -> 10
            Material.TIPPED_ARROW -> 10
            Material.LINGERING_POTION -> 10
            Material.SHIELD -> 10
            Material.TOTEM_OF_UNDYING -> 10
            Material.SHULKER_SHELL -> 10
            Material.IRON_NUGGET -> 10
            Material.KNOWLEDGE_BOOK -> 10
            Material.DEBUG_STICK -> 10
            Material.MUSIC_DISC_13 -> 10
            Material.MUSIC_DISC_CAT -> 10
            Material.MUSIC_DISC_BLOCKS -> 10
            Material.MUSIC_DISC_CHIRP -> 10
            Material.MUSIC_DISC_FAR -> 10
            Material.MUSIC_DISC_MALL -> 10
            Material.MUSIC_DISC_MELLOHI -> 10
            Material.MUSIC_DISC_STAL -> 10
            Material.MUSIC_DISC_STRAD -> 10
            Material.MUSIC_DISC_WARD -> 10
            Material.MUSIC_DISC_11 -> 10
            Material.MUSIC_DISC_WAIT -> 10
            Material.MUSIC_DISC_OTHERSIDE -> 10
            Material.MUSIC_DISC_5 -> 10
            Material.MUSIC_DISC_PIGSTEP -> 10
            Material.DISC_FRAGMENT_5 -> 10
            Material.TRIDENT -> 10
            Material.PHANTOM_MEMBRANE -> 10
            Material.NAUTILUS_SHELL -> 10
            Material.HEART_OF_THE_SEA -> 10
            Material.CROSSBOW -> 10
            Material.SUSPICIOUS_STEW -> 10
            Material.LOOM -> 10
            Material.FLOWER_BANNER_PATTERN -> 10
            Material.CREEPER_BANNER_PATTERN -> 10
            Material.SKULL_BANNER_PATTERN -> 10
            Material.MOJANG_BANNER_PATTERN -> 10
            Material.GLOBE_BANNER_PATTERN -> 10
            Material.PIGLIN_BANNER_PATTERN -> 10
            Material.GOAT_HORN -> 10
            Material.COMPOSTER -> 10
            Material.BARREL -> 10
            Material.SMOKER -> 10
            Material.BLAST_FURNACE -> 10
            Material.CARTOGRAPHY_TABLE -> 10
            Material.FLETCHING_TABLE -> 10
            Material.GRINDSTONE -> 10
            Material.SMITHING_TABLE -> 10
            Material.STONECUTTER -> 10
            Material.BELL -> 10
            Material.LANTERN -> 10
            Material.SOUL_LANTERN -> 10
            Material.SWEET_BERRIES -> 10
            Material.GLOW_BERRIES -> 10
            Material.CAMPFIRE -> 10
            Material.SOUL_CAMPFIRE -> 10
            Material.SHROOMLIGHT -> 10
            Material.HONEYCOMB -> 10
            Material.BEE_NEST -> 10
            Material.BEEHIVE -> 10
            Material.HONEY_BOTTLE -> 10
            Material.HONEYCOMB_BLOCK -> 10
            Material.LODESTONE -> 10
            Material.CRYING_OBSIDIAN -> 10
            Material.BLACKSTONE -> 10
            Material.BLACKSTONE_SLAB -> 10
            Material.BLACKSTONE_STAIRS -> 10
            Material.GILDED_BLACKSTONE -> 10
            Material.POLISHED_BLACKSTONE -> 10
            Material.POLISHED_BLACKSTONE_SLAB -> 10
            Material.POLISHED_BLACKSTONE_STAIRS -> 10
            Material.CHISELED_POLISHED_BLACKSTONE -> 10
            Material.POLISHED_BLACKSTONE_BRICKS -> 10
            Material.POLISHED_BLACKSTONE_BRICK_SLAB -> 10
            Material.POLISHED_BLACKSTONE_BRICK_STAIRS -> 10
            Material.CRACKED_POLISHED_BLACKSTONE_BRICKS -> 10
            Material.RESPAWN_ANCHOR -> 10
            Material.CANDLE -> 10
            Material.WHITE_CANDLE -> 10
            Material.ORANGE_CANDLE -> 10
            Material.MAGENTA_CANDLE -> 10
            Material.LIGHT_BLUE_CANDLE -> 10
            Material.YELLOW_CANDLE -> 10
            Material.LIME_CANDLE -> 10
            Material.PINK_CANDLE -> 10
            Material.GRAY_CANDLE -> 10
            Material.LIGHT_GRAY_CANDLE -> 10
            Material.CYAN_CANDLE -> 10
            Material.PURPLE_CANDLE -> 10
            Material.BLUE_CANDLE -> 10
            Material.BROWN_CANDLE -> 10
            Material.GREEN_CANDLE -> 10
            Material.RED_CANDLE -> 10
            Material.BLACK_CANDLE -> 10
            Material.SMALL_AMETHYST_BUD -> 10
            Material.MEDIUM_AMETHYST_BUD -> 10
            Material.LARGE_AMETHYST_BUD -> 10
            Material.AMETHYST_CLUSTER -> 10
            Material.POINTED_DRIPSTONE -> 10
            Material.OCHRE_FROGLIGHT -> 10
            Material.VERDANT_FROGLIGHT -> 10
            Material.PEARLESCENT_FROGLIGHT -> 10
            Material.FROGSPAWN -> 10
            Material.ECHO_SHARD -> 10
            Material.WATER -> 10
            Material.LAVA -> 10
            Material.TALL_SEAGRASS -> 10
            Material.PISTON_HEAD -> 10
            Material.MOVING_PISTON -> 10
            Material.WALL_TORCH -> 10
            Material.FIRE -> 10
            Material.SOUL_FIRE -> 10
            Material.REDSTONE_WIRE -> 10
            Material.OAK_WALL_SIGN -> 10
            Material.SPRUCE_WALL_SIGN -> 10
            Material.BIRCH_WALL_SIGN -> 10
            Material.ACACIA_WALL_SIGN -> 10
            Material.JUNGLE_WALL_SIGN -> 10
            Material.DARK_OAK_WALL_SIGN -> 10
            Material.MANGROVE_WALL_SIGN -> 10
            Material.BAMBOO_WALL_SIGN -> 10
            Material.OAK_WALL_HANGING_SIGN -> 10
            Material.SPRUCE_WALL_HANGING_SIGN -> 10
            Material.BIRCH_WALL_HANGING_SIGN -> 10
            Material.ACACIA_WALL_HANGING_SIGN -> 10
            Material.JUNGLE_WALL_HANGING_SIGN -> 10
            Material.DARK_OAK_WALL_HANGING_SIGN -> 10
            Material.MANGROVE_WALL_HANGING_SIGN -> 10
            Material.CRIMSON_WALL_HANGING_SIGN -> 10
            Material.WARPED_WALL_HANGING_SIGN -> 10
            Material.BAMBOO_WALL_HANGING_SIGN -> 10
            Material.REDSTONE_WALL_TORCH -> 10
            Material.SOUL_WALL_TORCH -> 10
            Material.NETHER_PORTAL -> 10
            Material.ATTACHED_PUMPKIN_STEM -> 10
            Material.ATTACHED_MELON_STEM -> 10
            Material.PUMPKIN_STEM -> 10
            Material.MELON_STEM -> 10
            Material.WATER_CAULDRON -> 10
            Material.LAVA_CAULDRON -> 10
            Material.POWDER_SNOW_CAULDRON -> 10
            Material.END_PORTAL -> 10
            Material.COCOA -> 10
            Material.TRIPWIRE -> 10
            Material.POTTED_OAK_SAPLING -> 10
            Material.POTTED_SPRUCE_SAPLING -> 10
            Material.POTTED_BIRCH_SAPLING -> 10
            Material.POTTED_JUNGLE_SAPLING -> 10
            Material.POTTED_ACACIA_SAPLING -> 10
            Material.POTTED_DARK_OAK_SAPLING -> 10
            Material.POTTED_MANGROVE_PROPAGULE -> 10
            Material.POTTED_FERN -> 10
            Material.POTTED_DANDELION -> 10
            Material.POTTED_POPPY -> 10
            Material.POTTED_BLUE_ORCHID -> 10
            Material.POTTED_ALLIUM -> 10
            Material.POTTED_AZURE_BLUET -> 10
            Material.POTTED_RED_TULIP -> 10
            Material.POTTED_ORANGE_TULIP -> 10
            Material.POTTED_WHITE_TULIP -> 10
            Material.POTTED_PINK_TULIP -> 10
            Material.POTTED_OXEYE_DAISY -> 10
            Material.POTTED_CORNFLOWER -> 10
            Material.POTTED_LILY_OF_THE_VALLEY -> 10
            Material.POTTED_WITHER_ROSE -> 10
            Material.POTTED_RED_MUSHROOM -> 10
            Material.POTTED_BROWN_MUSHROOM -> 10
            Material.POTTED_DEAD_BUSH -> 10
            Material.POTTED_CACTUS -> 10
            Material.CARROTS -> 10
            Material.POTATOES -> 10
            Material.SKELETON_WALL_SKULL -> 10
            Material.WITHER_SKELETON_WALL_SKULL -> 10
            Material.ZOMBIE_WALL_HEAD -> 10
            Material.PLAYER_WALL_HEAD -> 10
            Material.CREEPER_WALL_HEAD -> 10
            Material.DRAGON_WALL_HEAD -> 10
            Material.PIGLIN_WALL_HEAD -> 10
            Material.WHITE_WALL_BANNER -> 10
            Material.ORANGE_WALL_BANNER -> 10
            Material.MAGENTA_WALL_BANNER -> 10
            Material.LIGHT_BLUE_WALL_BANNER -> 10
            Material.YELLOW_WALL_BANNER -> 10
            Material.LIME_WALL_BANNER -> 10
            Material.PINK_WALL_BANNER -> 10
            Material.GRAY_WALL_BANNER -> 10
            Material.LIGHT_GRAY_WALL_BANNER -> 10
            Material.CYAN_WALL_BANNER -> 10
            Material.PURPLE_WALL_BANNER -> 10
            Material.BLUE_WALL_BANNER -> 10
            Material.BROWN_WALL_BANNER -> 10
            Material.GREEN_WALL_BANNER -> 10
            Material.RED_WALL_BANNER -> 10
            Material.BLACK_WALL_BANNER -> 10
            Material.BEETROOTS -> 10
            Material.END_GATEWAY -> 10
            Material.FROSTED_ICE -> 10
            Material.KELP_PLANT -> 10
            Material.DEAD_TUBE_CORAL_WALL_FAN -> 10
            Material.DEAD_BRAIN_CORAL_WALL_FAN -> 10
            Material.DEAD_BUBBLE_CORAL_WALL_FAN -> 10
            Material.DEAD_FIRE_CORAL_WALL_FAN -> 10
            Material.DEAD_HORN_CORAL_WALL_FAN -> 10
            Material.TUBE_CORAL_WALL_FAN -> 10
            Material.BRAIN_CORAL_WALL_FAN -> 10
            Material.BUBBLE_CORAL_WALL_FAN -> 10
            Material.FIRE_CORAL_WALL_FAN -> 10
            Material.HORN_CORAL_WALL_FAN -> 10
            Material.BAMBOO_SAPLING -> 10
            Material.POTTED_BAMBOO -> 10
            Material.VOID_AIR -> 10
            Material.CAVE_AIR -> 10
            Material.BUBBLE_COLUMN -> 10
            Material.SWEET_BERRY_BUSH -> 10
            Material.WEEPING_VINES_PLANT -> 10
            Material.TWISTING_VINES_PLANT -> 10
            Material.CRIMSON_WALL_SIGN -> 10
            Material.WARPED_WALL_SIGN -> 10
            Material.POTTED_CRIMSON_FUNGUS -> 10
            Material.POTTED_WARPED_FUNGUS -> 10
            Material.POTTED_CRIMSON_ROOTS -> 10
            Material.POTTED_WARPED_ROOTS -> 10
            Material.CANDLE_CAKE -> 10
            Material.WHITE_CANDLE_CAKE -> 10
            Material.ORANGE_CANDLE_CAKE -> 10
            Material.MAGENTA_CANDLE_CAKE -> 10
            Material.LIGHT_BLUE_CANDLE_CAKE -> 10
            Material.YELLOW_CANDLE_CAKE -> 10
            Material.LIME_CANDLE_CAKE -> 10
            Material.PINK_CANDLE_CAKE -> 10
            Material.GRAY_CANDLE_CAKE -> 10
            Material.LIGHT_GRAY_CANDLE_CAKE -> 10
            Material.CYAN_CANDLE_CAKE -> 10
            Material.PURPLE_CANDLE_CAKE -> 10
            Material.BLUE_CANDLE_CAKE -> 10
            Material.BROWN_CANDLE_CAKE -> 10
            Material.GREEN_CANDLE_CAKE -> 10
            Material.RED_CANDLE_CAKE -> 10
            Material.BLACK_CANDLE_CAKE -> 10
            Material.POWDER_SNOW -> 10
            Material.CAVE_VINES -> 10
            Material.CAVE_VINES_PLANT -> 10
            Material.BIG_DRIPLEAF_STEM -> 10
            Material.POTTED_AZALEA_BUSH -> 10
            Material.POTTED_FLOWERING_AZALEA_BUSH -> 10
            else -> 0
        }

    }

}